" https://git.corp.yahoo.com/shahar/dotfiles/blob/master/.vimrc

" show line number !!
set nu

" make the color on!
syntax on

" Comment out until finding a good color scheme
set t_Co=256

" tell vim how many columns a tab counts for 
set tabstop=2
" tab would be shown as spaces
set expandtab
" > and < would be 4 spaces
set shiftwidth=2
" http://stackoverflow.com/questions/1562336/tab-vs-space-preferences-in-vim
" super good explanation about how is softtabstop different than tabstop
set softtabstop=2

" http://vim.wikia.com/wiki/VimTip906: 
" In a console or terminal version of Vim, there is no standard procedure to paste text from another application. Instead, the terminal may emulate pasting by inserting text into the keyboard buffer, so Vim thinks the text has been typed by the user. After each line ending, Vim may move the cursor so the next line starts with the same indent as the last. However, that will change the indentation already in the pasted text.
set paste

" self-explained
set noswapfile

" line number is too conspicuous 
:highlight LineNr ctermfg=grey

" TODO: change the bg color of ctrl-p 

" Highlight problematic whitespace
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

set mouse=a

" Highlight search results
set hlsearch

" https://github.com/chrishunt/color-schemes
set background=dark
colorscheme base16-railscasts

highlight clear SignColumn
highlight VertSplit    ctermbg=236
highlight ColorColumn  ctermbg=237
highlight LineNr       ctermbg=236 ctermfg=240
highlight CursorLineNr ctermbg=236 ctermfg=240
highlight CursorLine   ctermbg=236
highlight StatusLineNC ctermbg=238 ctermfg=0
highlight StatusLine   ctermbg=240 ctermfg=12
highlight IncSearch    ctermbg=3   ctermfg=1
highlight Search       ctermbg=1   ctermfg=3
highlight Visual       ctermbg=3   ctermfg=0
highlight Pmenu        ctermbg=240 ctermfg=12
highlight PmenuSel     ctermbg=3   ctermfg=1
highlight SpellBad     ctermbg=0   ctermfg=1
